### PR TITLE
Refactor project-details handlers with bind

### LINKED ISSUE #7453: Selecting a discipline from the project details discipline input errors
From the "Project details" section within the project builder / lab, selecting a discipline causes an error that loads a blank page. The console logs `TypeError: this.setState is not a function`. The expected behavior is that the selected discipline tag would be selected and show within the input.

### PR DESCRIPTION
**Pull request by mcbouslog**
## Linked Issue and/or Talk Post
- closes #7453 
- I think introduced with #7431 refactor

## Describe your changes
- binds handlers in Class constructor

## How to Review
- What user actions should my reviewer step through to review this PR?
  - confirm bug: https://www.zooniverse.org/lab/1693?env=staging
    - change discipline, researcher, or other tag
    - note error
  - confirm fix: https://local.zooniverse.org:3735/lab/1693
    - change discipline, researcher, or other tag
    - note change as expected
- Are there plans for follow up PR’s to further fix this bug or develop this feature? no

### General UX
- [ ] Staging branch URL: https://pr-7454.pfe-preview.zooniverse.org/lab
- [ ] The component is accessible (double check especially if adding new code to this codebase). We recognize that not all legacy components of PFE will pass accessibility guidelines.
  - Can be used with a screen reader [BBC guide to VoiceOver](https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing-steps/voiceover-mac.html)
  - Can be used from the keyboard [WebAIM guide to keyboard testing](https://webaim.org/techniques/keyboard/#testing)

### Bug Fix
- [ ] The PR creator has listed user actions to use when testing if bug is fixed
- [ ] The bug is fixed
- [ ] Unit tests are added or updated

### CODE REVIEW

**Review by shaunanoordin — APPROVED** [review]
## PR Review

Affects: Lab (Project Builder) -> Edit Project Details

This PR fixes an issue where changing either 1. the researcher on the researcher quote, 2. disciplines tags, or 3. other tags, causes the whole webpage to crash.

Code changes:

- fix was implemented by adding function.bind(this) to the relevant event handlers, so they have the correct context to what 'this' is.

Dev notes:

- It should be noted that the other event handlers work because they have .bind applied on assignment (e.g. `handleInputChange.bind(this.props.project)`)
- The on researcher change, on discipline tag change, and on other tag change handlers however, were missed during the decaffeination of #7431. (Conversion of project-details.cjsx to project-details.jsx)

### Status

LGTM, thank you for catching this @mcbouslog . I'm going to run additional checks to see if there's anything else that was missed during the decaffeination.

**Comment by shaunanoordin** [comment]
As promised, I did some additional tests to ensure nothing else was missed during the decaffeination.[^1] I've rolled my testing notes together with the tests I've done for this PR.

[^1]: to be honest, these broad tests should've been done when I did 7431 instead of hyper-focusing tests on the multi-org projects. 

### Testing

Tested on this PR's staging branch.

Baseline tests plus 🔹 specific tests for this PR:

- Select a test project: https://pr-7454.pfe-preview.zooniverse.org/lab/2021?env=staging
- Change the project's name.
- Change the project's description.
- Change the project's introduction.
  - Use the markdown toolbar. (e.g. add bold text. use markdown preview. click on the "?" for the guide.)
- Change the project's workflow description.
- Change the researcher quote.
  - 🔹 Change the researcher
  - 🔹 Remove the researcher (press the 'x' button when a researcher is selected)
  - Change the quote
- 🔹 Change the Discipline Tags
  - 🔹 Add multiple tags, e.g. Biology, Arts
  - 🔹 Remove some/all tags.
-  🔹 Change the Other Tags
  - 🔹 Add multiple tags, e.g. "dev", "test"
  - 🔹 Remove some/all tags.
- Change the project's external links
  - Add a link, e.g. Classrooms -> https://classroom.zooniverse.org
  - Remove some/all links.
- Change the project's social links
  - Add a link, e.g. zooniverse.wordpress.com
  - Reset a link, i.e. click on the 'x' 
- Confirm all changes are registered by refreshing the page.

OK, full tests look good! 👍
