### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1568]
@edpaget Looks like you broke pagination in #1539 

@aweiksnar Can that method be injected with a mixin from the paginator?

```
TypeError: this.getPath is not a function
  return this.transitionTo(this.getPath(), {}, newSearch);
```

**Comment by aweiksnar** [comment]
If I remember correctly l originally used `location.pathname` there because react-router `getPath` wasn't working with non-hash-prefixed URLs, let me take another look. That may have been addressed with Ed's react-router patch

**Comment by chrissnyder** [comment]
My fault for not catching that. Could just https://github.com/edpaget/Panoptes-Front-End/blob/6e8ae8424ea4bf39b876635a0bfab27a32629322/app/talk/lib/paginator.cjsx#L23 be reverted to restore lost functionality? Ed's patch was accepted upstream, but might've not been published yet?

**Comment by aweiksnar** [comment]
Changing that back to location.pathname fixes it on all the pages I tried
